### ISSUE TITLE
I can't seem to get GladiusEx working on TWW beta, is there something I need to do?

### ISSUE THREAD

**Issue by Slo-reddit** [vendethiel/GladiusEx#101]
The addon loads on the addon list and I can enable it.

Typing /gex doesn't load the menu and nothing actually happens when you press enter (meaning, /gex message doesnt go away like it would if the addon hadn't loaded).

I tried taking the most recent github version and copying over the libs folder from a previous install and it didn't change anything.

Is there anything I can do to get GladiusEx working on beta?

PS. If you have a Patreon would love to buy you a coffee. This addon is insane.

**Comment by vendethiel** [comment]
It’s not ported to TWW. I’m not really playing wow anymore and haven’t been for a few years.
That was true also in the past, but a few people were generous enough to gift me the expac. At least this time I can download the beta, and I know already a few places I have to fix, so I might download it and get fixing…
Thanks for the kind words

**Comment by Slo-reddit** [comment]
>Thanks for the kind words

You're welcome and thanks for all your work on this project!

Hope you're having fun, whatever you're doing.
