### ISSUE TITLE
Healer pvp trinket cooldown incorrect

### ISSUE THREAD

**Issue by alexandersoto** [vendethiel/GladiusEx#107]
The pvp trinket CD for healers should be 90 seconds, but it's still registering as 2 minutes.

**Comment by alexandersoto** [comment]
@vendethiel are you open to contributions? I'd like to give this one a shot.

Would you prefer I update [cooldowns.lua](https://github.com/vendethiel/GladiusEx/blob/925f43172f0af160aab1428e43ab2a7b264c8589/modules/cooldowns.lua) or [LibCooldownTracker](https://github.com/vendethiel/LibCooldownTracker-10/blob/d387d6793f2fe58e36f2ed78971a611c26a224cc/library.lua) or somewhere else?

**Comment by vendethiel** [comment]
first I’d check if the cooldown tracking code for cataclysm support doesn’t impede retail cooldown tracking

**Comment by alexandersoto** [comment]
@vendethiel thanks - this seems to fix it for enemy healers. However party healers still have 2mins show for their trinket.

**Comment by vendethiel** [comment]
That sadly doesn't rely on the same bit of feature :(. It'd need special casing somewhere else.

**Comment by ManneN1** [comment]
It's quite easy to fix, all you need to do is set the CD of PvP trinkets in LibCooldownTracker to 90sec instead of 120sec.

**Comment by vendethiel** [comment]
> It's quite easy to fix, all you need to do is set the CD of PvP trinkets in LibCooldownTracker to 90sec instead of 120sec.

It's slightly more complex because it's only for healer specs, but still doable.

**Comment by ManneN1** [comment]
> > It's quite easy to fix, all you need to do is set the CD of PvP trinkets in LibCooldownTracker to 90sec instead of 120sec.
> 
> It's slightly more complex because it's only for healer specs, but still doable.

Yes, that's what I meant. A bit unclear from my side :)
