### ISSUE TITLE
Webhook API

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/GladiusEx#29]
Hi @slaren ,

It seems like ownership change broke the webhook system, I guess your API key is not considered valid for the project anymore.
Would you mind changing the webook here, or adding me admin to the repos so I can change it?

Thanks!

**Comment by slaren** [comment]
Hi, I tried to transfer ownership of this and the LCT repositories but I can't do it since you already have projects with the same name. Can you try renaming or deleting your forks ?

**Comment by vendethiel** [comment]
Hi -

Done. Deleted them.
Not sure you need to transfer ownership though; I think admin is enough.

**Comment by slaren** [comment]
I am no longer involved in the project and I have no interest in WoW anymore, it makes no sense for me to remain as the owner. You could also move development to your own fork, but by transferring ownership you should be able to keep the history of issues and pull requests.

**Comment by vendethiel** [comment]
@slaren Did you by any chance delete LibFunctional?

**Comment by slaren** [comment]
I did delete it from curseforge but it is still available here in github: https://github.com/slaren/LibFunctional-1.0 
I didn't realize that the repository from wowace was still being used, the pkgmeta will need to be updated.
