### ISSUE TITLE
Custom spell tracking/Covenant abilities

### ISSUE THREAD

**Issue by roanaes** [vendethiel/GladiusEx#31]
Hey, first of all I love this addon so much and I'm very thankful that you're maintaining it!

So with the addition of covenant abilities it's almost crucial to be able to track abilities like Convoke the Spirits, I wonder if it would be possible to add them to the cooldowns module or even better might be a new feature that would allow us to add/import custom spells. Do you think it's possible or maybe you're already working on something similiar?

Once again thank you so much for maintaining the addon! <3

**Comment by vendethiel** [comment]
Hey,

This is in the works :). See i.e. vendethiel/LibCooldownTracker-10#9
