### ISSUE TITLE
Update for 9.2?

### ISSUE THREAD

**Issue by Bodify** [vendethiel/GladiusEx#44]
Hey is this still being maintained for 9.2? Theres a few new PvP trinkets that would be nice to have added to the list :)

**Comment by vendethiel** [comment]
You’re right, I should add those. I only saw one for now, is there a list with ID and duration?

**Comment by Bodify** [comment]
All the new trinkets are listed under this quest: https://www.wowhead.com/quest=65649/a-new-deal
Only the first two, Fastidious Resolve and Echoing Resolve, are replacement for your standard PvP trinket (Medallion/Adaptation).

So I believe these are the effects you're looking for:
https://www.wowhead.com/spell=363117/gladiators-fastidious-resolve
and
https://www.wowhead.com/spell=363121/gladiators-echoing-resolve

However they don't seem to add any buffs on the player using them, just like Adaptation, but I could be wrong. I haven't seen too many of them yet because most people went with the "Cosmic Resonator" trinket for damage first week, but u can choose another one next week so expecting to see it a lot more then of people testing it.

I would also love to have a few auras added to the list. All of them being Hunter specific.
Chimaeral Sting (PvP Talent) adds 3 effects to the enemy target. Only the second effect should arguably be added (3 second silence, Spider Venom, spellid 356727) but also having the first effect (90% slow, Scorpid Venom, spellid 356723) would be nice as a lower prio one for both Hunters and others to be able to spot and time when the silence will take effect.

Another aura is a 4 second stun from another Hunter PvP Talent called "Consecutive Concussion" which has spellid 357021

**Comment by vendethiel** [comment]
> All cooldowns reset every short round but GladiusEx doesn't take that into consideration.

I need to check if there's an event for new rounds.

**Comment by Bodify** [comment]
ARENA_PREP_OPPONENT_SPECIALIZATIONS,ARENA_TEAM_ROSTER_UPDATE,ARENA_OPPONENT_UPDATE,PLAYER_PVP_TALENT_UPDATE,PLAYER_ENTERING_WORLD

Any of these relevant during new rounds? I don't have the experience to test or edit lua unfortunately.

**Comment by vendethiel** [comment]
The last one is, I’ll take a look, thanks

**Comment by nrteck0** [comment]
In case this helps, this is the spell id of the gladiator's resolve buff that would really help to add to the pvp trinkets section:

362699

It's the same buff for both trinkets but can have stacks depending on which one you use, so if you could show stacks also that'd be great. using tmw for this in the meantime. The one with stacks has a 3min cd, other one has no cd so it would just be helpful to track the duration of the buff in the place of the trinket.

**Comment by Bodify** [comment]
> In case this helps, this is the spell id of the gladiator's resolve buff that would really help to add to the pvp trinkets section:
> 
> 362699
> 
> It's the same buff for both trinkets but can have stacks depending on which one you use, so if you could show stacks also that'd be great. using tmw for this in the meantime. The one with stacks has a 3min cd, other one has no cd so it would just be helpful to track the duration of the buff in the place of the trinket.

I did already add this to auras yes. It's a buff and should just be tracked on auras like every other buff. But seeing which trinket they have equipped where you normally see medallion would be key if that is possible to do. Just like how Adaptation and Relentless shows.



> I just published a new version with a few fixes, I'll get back into the actual code this week hopefully.

I downloaded it and been using it since. I haven't really noticed any changes myself though.

**Comment by vendethiel** [comment]
> But seeing which trinket they have equipped where you normally see medallion would be key if that is possible to do

New versions will have them. No guarantees they work, but I added them the same manner the other pvp trinkets are.



> I downloaded it and been using it since. I haven't really noticed any changes myself though.

If you use the auras module you'll enjoy your game no longer crashing :).



> In case this helps, this is the spell id of the gladiator's resolve buff that would really help to add to the pvp trinkets section:
> 
> 362699

Should this be a super-low-prio classicon?

> I would also love to have a few auras added to the list. All of them being Hunter specific. Chimaeral Sting (PvP Talent) adds 3 effects to the enemy target. Only the second effect should arguably be added (3 second silence, Spider Venom, spellid 356727) but also having the first effect (90% slow, Scorpid Venom, spellid 356723) would be nice as a lower prio one for both Hunters and others to be able to spot and time when the silence will take effect.
> 
> Another aura is a 4 second stun from another Hunter PvP Talent called "Consecutive Concussion" which has spellid 357021

Please open a new issue for that so I can track it separately.

**Comment by vendethiel** [comment]
First batch in 17804e3c12efd5bed37b883b9e4aa702bf50fea2, will fix other things in gex and publish a new v.

**Comment by vendethiel** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/199499/158474271-7aac8557-d355-47db-b03c-31c575ad84bd.png">
Example with the in-dev version

**Comment by nrteck0** [comment]
Looks great, thank you!

**Comment by Bodify** [comment]
> > In case this helps, this is the spell id of the gladiator's resolve buff that would really help to add to the pvp trinkets section:
> > 362699
> 
> Should this be a super-low-prio classicon?
It's a pretty important aura, but then again so is seeing how long is left of the first cc you put on for example. I think a low-ish aura prio would be the correct way to filter it yes but for me personally I've also added a weakaura next to GEX's auras specificly for these trinket buffs and I feel like that is what most people would do and what makes the most sense. 

> > I would also love to have a few auras added to the list. All of them being Hunter specific. Chimaeral Sting (PvP Talent) adds 3 effects to the enemy target. Only the second effect should arguably be added (3 second silence, Spider Venom, spellid 356727) but also having the first effect (90% slow, Scorpid Venom, spellid 356723) would be nice as a lower prio one for both Hunters and others to be able to spot and time when the silence will take effect.
> > Another aura is a 4 second stun from another Hunter PvP Talent called "Consecutive Concussion" which has spellid 357021
> 
> Please open a new issue for that so I can track it separately.
Will do.

> <img alt="image" width="415" src="https://user-images.githubusercontent.com/199499/158474271-7aac8557-d355-47db-b03c-31c575ad84bd.png">
> 
> Example with the in-dev version
This is looking great, exactly the way I hoped it would!

**Comment by Bodify** [comment]
Any update on the in-dev version? I also wanted to ask if it's possible to track DR's from the start instead of finish? I know the addon Diminish does this and I might switch over to that for DR tracking if its not possible with ez fix in GladiusEx

**Comment by vendethiel** [comment]
> Any update on the in-dev version?

I wasn't home this week so I haven't been able to work on it.
I can publish the version I have it's just missing a few things (rogue disarm, stuff like aegis)

**Comment by vendethiel** [comment]
I just published the 9.2 patch (v2.2), will work on the next version this weekend and hopefully publish it then.

**Comment by Bodify** [comment]
Thank you! I'll try it out tomorrow :)
