### ISSUE TITLE
[BC Classic] Lua errors on release 2.1

### ISSUE THREAD

**Issue by boktai1000** [vendethiel/GladiusEx#45]
Using it in BC Classic, BugSack won't even show them all because there appears to be 421x (null) but copy pasting what it looks like to me

![image](https://user-images.githubusercontent.com/9054563/158269692-ad40330d-decd-4f9f-933e-a8f37e8afbd1.png)

**Comment by vendethiel** [comment]
Ok, interesting. I changed the packager, might be why. Shouldn’t be too broken nevertheless.
