### ISSUE TITLE
LibRangeCheck

### ISSUE THREAD

**Issue by Flamanis** [vendethiel/GladiusEx#70]
Hey man, apologies for bringing this up again. I just wanted to mention the LibRangeCheck issue/change that you merged last month. CF doesn't have an updated release so we're still getting reports in other addons about it. Just wanted to bring this up again with you and see if you needed any testing or such for getting a new version released with the up to date library.

**Comment by vendethiel** [comment]
You're right, I haven't cut a release in a bit. I just pushed 2.6.3.

**Comment by Flamanis** [comment]
Thank you :)

**Comment by vendethiel** [comment]
File is approved.
