### ISSUE TITLE
Party frame HP color problems in solo shuff

### ISSUE THREAD

**Issue by wwdes** [vendethiel/GladiusEx#80]
The addon has problems updating the healthbar color and/or class icon when new round starts. It results in mismatch between icon and healthbar. Very confusing. Doing /reload fixes the issue for the current round only.

**Comment by vendethiel** [comment]
Can you please provide a screenshot?

**Comment by wwdes** [comment]
Sorry, im not going in to solo with this addon because of this and other problems. There is not much you can learn from a screenshot anyway. It is just as i described, the icons dont match the healthbar color when a new round starts. So either the icon or the healthbar is not being updated properly.

**Comment by vendethiel** [comment]
No reproduction.

**Comment by vendethiel** [comment]
Try disabling arena frames in BigDebuffs however, because what looks like GladiusEx may in fact be BigDebuffs.

**Comment by wwdes** [comment]
It’s not bigdebuffs. Its the class icon of the party frame in gladiusex, when its set to show specialization. Doesnt matter of its sideview or main icon. It fails to update when rounds change. Please dont discard this. I am a programmet my self, and know how hard it is to progrmmaticalmy determine specializations in the game. Although, i suspect the issue is simpler as the icons update correctly when reloading.
