### ISSUE TITLE
Arena frames are not showing

### ISSUE THREAD

**Issue by taras-koval** [vendethiel/GladiusEx#84]
Recently updated the addon, now the arena frames are not showing. What could be the reason?

**Comment by vendethiel** [comment]
What wow version is that?

**Comment by taras-koval** [comment]
3.4.3

**Comment by taras-koval** [comment]
I installed the previous version of the addon (2.6.4) and the arena frames are working again.

**Comment by vendethiel** [comment]
So 2.7 breaks it too, not only 2.7.1?

**Comment by taras-koval** [comment]
I dont know, I can't install 2.7 using curseforge. Prev available version is 2.6.4. I guess 2.7 works fine, because i update addons almost every day

**Comment by vendethiel** [comment]
Ah, I think 2.7 wasn't tagged as available for wrath, only for retail. This is still manual....

I pushed 2.7.2 just now, I hope that fixes it.

**Comment by taras-koval** [comment]
Updated to 2.7.2, works, thanks!
