### ISSUE TITLE
DRList multiple categories

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/GladiusEx#88]
https://github.com/wardz/DRList-1.0/commit/e68df945d09e08012ab5317d9dfb54f855577b85

**Comment by ManneN1** [comment]
This was solved back in https://github.com/vendethiel/GladiusEx/commit/12a6eeb40d7c925aea2ffa53ab3545a5724760d0 as far as I can tell (Deep Freeze DRs both Stun and Incap on Cata, and it's visualized properly in GladiusEx).
